### ISSUE TITLE
[Bug] Recent Events gets flooded by donations

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2567] opened 2021-10-03 20:36 UTC
PhantomBot Version: nightly build sept 29 2021
O/S Version: linux
Java Version: JRE 8
Web Browser Version (if Panel related):

Detailed Description:
I've recently upgraded from 3.4.2 to the nightly build from sept 29. When I logged on to my bot the other day, I saw that revent events got flooded by donations from far earlier. It seems like every donation gets repeated twice a day. All of this started on friday and events from September are nowhere to be found.
The bot is connected to Streamlabs so maybe there is something wrong on their end. Maybe you could look into it :)

Steps to Reproduce:
Unknown

Logs:
Sadly none

Screenshots (if applicable):

**Comment by Alucard2112** [comment] 2021-10-05 11:37
It happened again. Yesterday and today the events got flooded with donations I received some time ago.
I do have a second bot running without a connection to streamlabs and that one is fine.
So it seems that the problem is at least isolated to tips and maybe even to Streamlabs.
I hope this helps :)

**Comment by gmt2001** [comment] 2021-10-05 22:43
Should be fixed in new nightly. I forced the build to start now, so it should be available shortly.

The issue is expected to happen 1 more time upon starting the bot after downloading the new version. After that occurrence, the fixed donation tracking should kick in and prevent it from happening again.

Re-open this ticket if it happens again, other than the expected occurrence upon updating

**Comment by dungi** [comment] 2021-11-17 15:13
I have the same issue with StreamElements Donations.

**Closed as completed** 2021-11-20 06:10 UTC
Labels: bug
