### ISSUE TITLE
Bot needs manual restart before & after the stream

### ISSUE THREAD

**Issue by BluesBroBo** [PhantomBot/PhantomBot#2564] opened 2021-09-28 22:21 UTC
PhantomBot Version: 3.4.7
O/S Version: Raspian Buster 10
Java Version: 11.0.4
Web Browser Version (if Panel related): /

Detailed Description:
The bot seems to have problems recognizing the start or the end of a stream. Settings that are supposed to start at the beginning of a stream, like posting a message on discord, setting his status to streaming, recognizing which game is played, opening the fitting death counter, it doesn't send the greetings for viewers, etc. do not set themselves until the bot is manually restarted with the "sudo systemctl restart phantombot" command. In the same way, the bot doesnt reset its discord status to normal and doesn't recognize the stream ended after a stream until it is manually restarted in the same way. I tried letting it run for a whole day but it never stopped until I restarted it. The problem exists since multiple PhantomBot versions and was present on my raspberry pi 3 aswell my new raspberry pi 4

Steps to Reproduce:
The bot runs 24/7 and posts timers in chat even when I'm offline. At the beginning of a stream, the named issues show that it didn't recognize the start. After the stream, the other named issues shows that it didn't recognzie the end of the stream.

Logs:
The problem occurs at the beginning and end of every stream multiple times a week. I attached todays logs as it happened today again.

[stacktraces_28-09-2021.txt](https://github.com/PhantomBot/PhantomBot/files/7247595/stacktraces_28-09-2021.txt)
[private-messages_28-09-2021.txt](https://github.com/PhantomBot/PhantomBot/files/7247596/private-messages_28-09-2021.txt)
[event_28-09-2021.txt](https://github.com/PhantomBot/PhantomBot/files/7247597/event_28-09-2021.txt)
[core-warnings_28-09-2021.txt](https://github.com/PhantomBot/PhantomBot/files/7247598/core-warnings_28-09-2021.txt)
[core-error_28-09-2021.txt](https://github.com/PhantomBot/PhantomBot/files/7247599/core-error_28-09-2021.txt)

**Comment by gmt2001** [comment] 2021-09-28 22:53
Duplicate of #2527 

Will keep your logs and info in mind as I try to resolve this, but closing this issue

**Closed as completed by gmt2001** 2021-09-28 22:53 UTC
Labels: bug, duplicate
