### ISSUE TITLE
disable chat commands for quote disables web panel ability to change quotes

### ISSUE THREAD

**Issue by arrowgent** [PhantomBot/PhantomBot#2648] opened 2022-01-22 01:42 UTC
PhantomBot Version:
PhantomBot Version: 3.5.0.2 (stable) (Revision: 65122ce)
Operating System: Linux
Java Version: 11.0.11+9-LTS-194

Detailed Description:
disabling default commands !addquotesilent and !delquotesilent
disables the ability to add and delete quotes in the panel

!chat !commands !should !not !effect !this !in !the !panel

Steps to Reproduce:
go to
commands default
edit !addquotesilent disable
edit !delquotesilent disable

go to Quotes
click +Add quote
nothing happens

click Delete trashcan
nothing happens

**Comment by gmt2001** [comment] 2022-03-27 14:14
Closing as this is intended behavior. The silent commands were specifically added in for the panel. The way the panel handles this may be updated to something more sensible in the future though

**Closed as completed by gmt2001** 2022-03-27 14:14 UTC
